config/routes.rb
Rails.application.routes.draw do
  resources :donations, only: [:create, :new]
  root 'donations#new'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/donations_controller.rb
require 'json'
require 'faraday'
require 'stripe'

class DonationsController < ApplicationController

  def new
    @user_id = params[:user_id] if params[:user_id]
    @charity_name = params[:charity_name]
    @submission_id = params[:submission_id]
    @charity_id = params[:charity_id]
    @amount = params[:amount] ? (params[:amount]).to_i * 100 : 300
    @charity_category_id = params[:charity_category_id]
    @contact_me = params[:contact_me]
    @first_name = params[:first_name]
    @last_name = params[:last_name]
    @phone = params[:phone]

  end

  def create
    @conn = Faraday.new(:url => 'http://www.smallchangegiving.co') do |faraday|
      faraday.request  :url_encoded             # form-encode POST params
      faraday.response :logger                  # log requests to STDOUT
      faraday.adapter  Faraday.default_adapter  # make requests with Net::HTTP
    end

    @user_id = params[:user_id]
    @charity_name = params[:charity_name]
    @submission_id = params[:submission_id]
    @charity_id = params[:charity_id]
    @amount = params[:amount] ? (params[:amount]).to_i * 100 : 300
    @email = params[:email]
    @charity_category_id = params[:charity_category_id]
    @contact_me = params[:contact_me]
    @first_name = params[:first_name]
    @last_name = params[:last_name]
    @phone = params[:phone]

    # if params[:email]
    #   customer = Stripe::Customer.create(
    #     :email => params[:email],
    #     :source  => params[:stripeToken]
    #   )
    # end

    charge = Stripe::Charge.create(
      # :customer    => customer.id,
      :source    => params[:stripeToken],
      :amount      => @amount,
      :description => @charity_name,
      :currency    => 'aud'
    )

    # Change these to params
    payload = {:donation => {:amount => @amount, :email => @email, :phone => @phone, :first_name => @first_name, :last_name => @last_name, :charity_category_id => @charity_category_id, :contact_me => @contact_me, :charity_id => @charity_id, :submission_id => @submission_id, :user_id => @user_id, :charity_name => params[:charity_name]}}
    # payload = {:donation => {:amount => 1000, :charity_id => 1, :submission_id => 98,:user_id => 1,:charity_name => "Greenpeace"}}

    if charge['paid'] == true
      response = @conn.post "/donations", payload

      # if response.status == 200
        if params[:email]
          redirect_to "http://www.smallchangegiving.co/thanks?email=" + @email
        else
          redirect_to "http://www.smallchangegiving.co/thanks"
        end
      # end
    end

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_donation_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_payment_form.html.erb
<div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
  <%= form_tag donations_path, id: 'payment-form', method: :post do %>


  <div class="alert alert-danger" role="alert" id="error-msg"><span class="payment-errors"></span></div>

  <%= hidden_field_tag :user_id, params[:user_id] %>
  <%= hidden_field_tag :submission_id, params[:submission_id] %>
  <%= hidden_field_tag :charity_id, params[:charity_id] %>
  <%= hidden_field_tag :charity_category_id, params[:charity_category_id] %>
  <%= hidden_field_tag :charity_name, params[:charity_name] %>


  <div class="form-group">
    <label class="sr-only" for="amount">Amount (in dollars)</label>
    <div class="input-group">
      <div class="input-group-addon"><i class="fa fa-usd"></i></div>
      <% if params[:amount] %>
        <input type="text" class="form-control custom-input" id="amount" value="<%= params[:amount].to_i/100%>.00" name="amount">
      <% else %>
        <input type="text" class="form-control custom-input" id="amount" name="amount" placeholder="Amount (AUD)" required>
      <% end %>
    </div>
  </div>

    <% unless params[:user_id] %>
      <div class="form-group">
        <label class="sr-only" for="first_name">First Name</label>
        <div class="input-group">
          <div class="input-group-addon"><i class="fa fa-user" aria-hidden="true"></i></div>
          <input type="first_name" class="form-control custom-input" id="first_name" placeholder="First Name" name="first_name" required>
        </div>
      </div>
      <div class="form-group">
        <label class="sr-only" for="last_name">Last Name</label>
        <div class="input-group">
          <div class="input-group-addon"><i class="fa fa-users" aria-hidden="true"></i></div>
          <input type="last_name" class="form-control custom-input" id="last_name" placeholder="Last Name" name="last_name" required>
        </div>
      </div>
      <div class="form-group">
        <label class="sr-only" for="email">Email</label>
        <div class="input-group">
          <div class="input-group-addon"><i class="fa fa-envelope"></i></div>
          <input type="email" class="form-control custom-input" id="email" placeholder="Email" name="email" required>
        </div>
      </div>
      <div class="form-group">
        <label class="sr-only" for="phone">Mobile</label>
        <div class="input-group">
          <div class="input-group-addon">  <i class="fa fa-mobile" aria-hidden="true"></i></div>
          <input type="phone" class="form-control custom-input" id="phone" placeholder="Mobile" name="phone" required>
        </div>
      </div>
    <% end %>
    <div class="form-group">
      <label class="sr-only" for="card-number">Credit card number</label>
      <div class="input-group">
        <div class="input-group-addon"><i class="fa fa-credit-card-alt"></i></div>
        <input type="text" class="form-control custom-input" id="card-number" placeholder="Card Number" data-stripe="number" required>
      </div>
    </div>
    <div class="row">
      <div class="col-md-8">
        <div class="form-group">
          <label class="sr-only" for="month">Month</label>
          <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
            <input type="text" class="form-control custom-input" id="month" placeholder="MM" data-stripe="exp-month" required>
            <span class="input-group-addon white-text">/</span>
            <input type="text" class="form-control custom-input" id="year" placeholder="YYYY" data-stripe="exp-year" required>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="form-group">
          <label class="sr-only" for="cvc-number">CVC Number</label>
          <div class="input-group">
            <div class="input-group-addon"><i class="fa fa-lock"></i></div>
            <input type="text" class="form-control custom-input" id="cvc-number" placeholder="CVC" data-stripe="cvc" required>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12">
      <div class="form-group">
        <div class="input-group">
          <input type="checkbox" value="true" checked="checked" name="contact_me" id="user_remember_me">
          <label class="terms-label" for="user_remember_me">Happy to be contacted <%= "by #{@charity_name}" if @charity_name.present? %> to find out how I can get more involved
          </label>
        </div>
      </div>
    </div>
    <div class="pay-button">
      <button type="submit" class="btn btn-black btn-block">Take Action</button>
    </div>
    <div class="col-xs-12">
     <p class="terms-and-conditions">By completing the donation you are agreeing to the <a href="http://smallchangegiving.co/terms">terms and conditions</a></p>
    </div>
  </div>
  <% end %>
</div>

<div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
  <div class="stripe-image">
    <center>
      <img src="https://res.cloudinary.com/small-change/image/upload/v1462347701/outline_jfxm6l.png" width="100px">
    </center>
  </div>
</div>

<!-- </form> -->

<script type="text/javascript" src="https://js.stripe.com/v2/"></script>

<script type="text/javascript">
  // This identifies your website in the createToken call below
  Stripe.setPublishableKey('<%= ENV["SCP_STRIPE_PUBLISHABLE_KEY"] %>');

  // jQuery(function($) {
  //   $('#payment-form').submit(function(event) {
  //     var $form = $(this);

  //     // Disable the submit button to prevent repeated clicks
  //     $form.find('button').prop('disabled', true);

  //     Stripe.card.createToken($form, stripeResponseHandler);

  //     // Prevent the form from submitting with the default action
  //     return false;
  //   });
  // });

  $(function() {
    var $form = $('#payment-form');
    $form.submit(function(event) {
      // Disable the submit button to prevent repeated clicks:
      $form.find('button').prop('disabled', true);

      // Request a token from Stripe:
      Stripe.card.createToken($form, stripeResponseHandler);

      // Prevent the form from being submitted:
      return false;
    });
  });
</script>

<script>
$( document ).ready(function() {
  $( "#error-msg" ).hide();
});

function stripeResponseHandler(status, response) {
  var $form = $('#payment-form');

  if (response.error) {
    // Show the errors on the form
    $( "#error-msg" ).show(50);
    $form.find('.payment-errors').text(response.error.message);
    $form.find('button').prop('disabled', false);
  } else {
    // response contains id and card, which contains additional card details
    var token = response.id;
    // Insert the token into the form so it gets submitted to the server
    $form.append($('<input type="hidden" name="stripeToken" />').val(token));
    // and submit
    $form.get(0).submit();
  }
};
</script>

app/views/donations/new.html.erb
<div id='payments-page'>
  <div class='container'>
    <div class=''>
      <% if @charity_name %>
        <div class="hidden-xs">
          <h2 class='sc-header'>Thanks for supporting <%= @charity_name %>.</h2>
        </div>
        <div class="visible-xs">
          <h2 class='sc-header-mobile'>Thanks for supporting <%= @charity_name %>.</h2>
        </div>
      <% else %>
      <div class="hidden-xs">
        <h2 class="sc-header">Thanks for your support!</h2>
      </div>
      <div class="visible-xs">
        <h2 class="sc-header-mobile">Thanks for your support!</h2>
      </div>
      <% end %>
    </div>
    <%= render 'payment_form' %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-static-bottom">
  <div class="container">
    <div class="col-sm-10 col-sm-offset-1">
      <div class="footer-links">
        <ul class="nav navbar-nav navbar-left text-center">
          <div class="row">
            <div class="col-xs-4">
              <li><%= link_to "FAQ", "http://www.smallchangegiving.co/faq", class: 'navbar-text' %></li>
            </div>
            <div class="col-xs-4">
              <li><%= link_to "Team", "http://www.smallchangegiving.co/founders", class: 'navbar-text' %></li>
            </div>
            <div class="col-xs-4">
              <li><%= link_to "Terms", "http://www.smallchangegiving.co/terms", class: 'navbar-text' %></li>
            </div>
          </div>
        </ul>
        <ul class="nav navbar-nav navbar-right text-center">
          <div class="col-xs-4">
            <li><a href="https://www.facebook.com/smallchangegiving/likes"><i class="fa fa-facebook fa-nav"></i></a></li>
          </div>
          <div class="col-xs-4">
            <li><a href="https://twitter.com/smallchangeAU"><i class="fa fa-twitter fa-nav"></i></a></li>
          </div>
          <div class="col-xs-4">
            <li><a href="https://www.instagram.com/smallchangegiving/"><i class="fa fa-instagram fa-nav"></i></a></li>
          </div>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-static-top">
  <div class="container">
    <div class="col-sm-10 col-sm-offset-1">
      <div class="navbar-header">
        <a href="<%= "http://www.smallchangegiving.co/" %>" class="navbar-brand navbar-text">
          SMALL CHANGE
        </a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to ('<i class="fa fa-line-chart"></i> Trending').html_safe, "http://www.smallchangegiving.co/submissions/", class: 'navbar-text' %></li>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Small Change Donation</title>
  <%= favicon_link_tag(source='https://res.cloudinary.com/small-change/image/upload/v1456809563/smallchangelogo_e8vtaw.png') %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<%= render 'layouts/header' %>

<%= yield %>

<%= render 'layouts/footer' %>
</body>
</html>